#!/usr/bin/env python3

import argparse
from src.install import Packages
import sys

version = '0.0.1'

def main() -> None:
	parser = argparse.ArgumentParser("Ascent Package Manager")
	parser.add_argument('-S', '--install', dest="install", nargs='*', help="Install one or more packages")
	parser.add_argument('-s', '--search', dest="search", nargs='*', help="Search for one or more packages")
	parser.add_argument('-v', '--version', action='version', version=f'%(prog)s {version}')
	args = parser.parse_args()

	if len(sys.argv) < 2:
		parser.print_help()
		sys.exit(1)

	if args.install:
		install = Packages(args.install, "etc/ascent.conf")
		install.install()
	
	if args.search:
		install = Packages(args.search, "etc/ascent.conf")
		install.search()
	

if __name__ == '__main__':
	main()