#!/usr/bin/env python3

import argparse
from src.install import Packages

version = '0.0.1'

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('-S', '--install', dest="install", nargs='*', help="Install a package")
	parser.add_argument('-v', '--version', action='version', version=f'%(prog)s {version}')
	args = parser.parse_args()

	if args.install:
		install = Packages(args.install, "etc/ascent.conf")
		install.install()

if __name__ == '__main__':
	main()